# -*- coding: utf-8 -*-
"""alguma coisa qualquer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p6TQjitZuTSEKVGtYEv7dSeJ1M1qw921

Escreva um programa que leia, separadamente, dia, mês e ano da data atual. Leia, da mesma forma, a data de
nascimento de uma pessoa, calcule e escreva a idade exata em anos
"""

dia_hoje = int(input())
mes_hoje = int(input())
ano_hoje = int(input())

dia_nasc = int(input())
mes_nasc = int(input())
ano_nasc = int(input())

idade = ano_hoje - ano_nasc

if mes_hoje < mes_nasc:
  idade -= 1
elif dia_hoje < dia_nasc:
  idade -= 1


print(idade)